name: Build binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump"
        required: true
        type: choice
        options:
          - none
        default: "none"

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.5

      - name: Install dependencies
        run: bun install

      - name: Build app
        run: |
          cd apps/server
          bun run build --bump ${{ inputs.bump }}

      - name: Get new version
        id: get_version
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Get short SHA
        id: get_short_sha
        run: echo "::set-output name=sha::$(git rev-parse --short origin/main)"

      - name: Identify user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}-${{ steps.get_short_sha.outputs.sha }}
          name: v${{ steps.get_version.outputs.version }}-${{ steps.get_short_sha.outputs.sha }}
          draft: true
          files: |
            apps/server/build/out/sharkord-linux-x64
            apps/server/build/out/sharkord-linux-arm64
            apps/server/build/out/sharkord-windows-x64.exe
            apps/server/build/out/sharkord-macos-x64
            apps/server/build/out/sharkord-macos-arm64
            apps/server/build/out/release.json
          body: |
            ## Changes
            (TODO)
